name: HxFlutter
description: Laurie Marceau's Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_blue: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  scoped_model: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/activity.png
    - assets/images/battery.png
    - assets/images/bluetooth_icon.png
    - assets/images/bluetooth_scanning.png
    - assets/images/breathing_rate.png
    - assets/images/cadence.png
    - assets/images/heart_rate.png
    - assets/images/hx_device.png
    - assets/images/steps.png